Compile reactive with "-parameters"
This is needed to prevent the runtime error
```
IllegalStateException: Cannot set property id because no setter, no wither and it's not part of the persistence constructor
```
which could also be fixed by adding `@lombok.With` to `OutboxRecord.id`,
and (if `@With` would have been used as a fix) to prevent the next issue
```
org.springframework.data.mapping.MappingException: Parameter org.springframework.data.mapping.Parameter@f0db254e does not have a name
```

The first issue occurred also in [this
build](https://github.com/tomorrow-one/transactional-outbox/actions/runs/7228060080/job/19696823732?pr=265)
for PR #265 and was once reported with issue #252

Note, that it's not entirely clear which change in Spring or R2DBC
exactly caused this new issue, we only see that it's needed. Maybe it's
also somehow related to issue #234