Use kafka-testcontainers in outbox-kafka-spring
This gets rid of `EmbeddedKafkaRule` which uses `EmbeddedKafkaBroker`,
and helps to transition to a new kafka-clients version (3.6.x), which
is currently blocked due to incompatibilities with spring-kafka-test.
E.g. https://github.com/tomorrow-one/transactional-outbox/actions/runs/7142357304/job/19451488844?pr=253
failed with
```
Caused by:
        java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: Failed to obtain TestUtils.createBrokerConfig method; client version: 3.6.1 [in thread "Test worker"]
            at org.springframework.kafka.test.EmbeddedKafkaBroker.<clinit>(EmbeddedKafkaBroker.java:154)
            at org.springframework.kafka.test.rule.EmbeddedKafkaRule.<init>(EmbeddedKafkaRule.java:60)
```