Prevent kafka server/clients version conflict
By specifying kafka server version explicitly. An alternative could be
to use testcontainers-kafka.

Without this, tests were failing with
```
java.lang.NoSuchMethodError: 'org.apache.kafka.common.feature.Features org.apache.kafka.common.feature.Features.finalizedFeatures(java.util.Map)'
	at kafka.server.BrokerFeatures.defaultFinalizedFeatures(BrokerFeatures.scala:44) ~[kafka_2.13-3.2.3.jar:?]
	at kafka.controller.KafkaController.enableFeatureVersioning(KafkaController.scala:388) ~[kafka_2.13-3.2.3.jar:?]
```